import React from 'react';
import { redirect } from 'next/navigation';
import { createServerSideClient } from '@/lib/supabase';
import prisma from '@/lib/prisma';
import { getPlanById } from '@/lib/billing/plans';
import AppShellClient from '@/components/shared/AppShellClient';

interface DashboardLayoutProps {
  children: React.ReactNode;
}

export default async function DashboardLayout({ children }: DashboardLayoutProps) {
  const supabase = await createServerSideClient();
  
  // 1. Authenticate user context server-side
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    redirect('/login');
  }

  // 2. Query public profile configuration and usage parameters from PostgreSQL database
  const dbUser = await prisma.user.findUnique({
    where: { id: user.id },
    select: {
      role: true,
      subscription: true,
      _count: {
        select: {
          appeals: true, // Counts total appeals generated by the user
        },
      },
    },
  });

  const notifications = await prisma.notification.findMany({
    where: { userId: user.id },
    orderBy: { createdAt: 'desc' },
    take: 10,
  });

  const userRole = dbUser?.role || 'USER';
  const usageCount = dbUser?._count?.appeals || 0;
  
  const planId = dbUser?.subscription?.status === 'active' ? dbUser.subscription.planId : 'free';
  const plan = getPlanById(planId);
  const usageLimit = plan.limit;

  return (
    <AppShellClient
      userEmail={user.email || 'user@example.com'}
      userRole={userRole}
      usageCount={usageCount}
      usageLimit={usageLimit}
      initialNotifications={notifications}
    >
      {children}
    </AppShellClient>
  );
}
