import React from 'react';
import { redirect } from 'next/navigation';
import { createServerSideClient } from '@/lib/supabase';
import prisma from '@/lib/prisma';
import { getPlanById } from '@/lib/billing/plans';
import AppShellClient from '@/components/shared/AppShellClient';

interface DashboardLayoutProps {
  children: React.ReactNode;
}

export default async function DashboardLayout({ children }: DashboardLayoutProps) {
  const supabase = await createServerSideClient();
  
  // 1. Authenticate user context server-side
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    redirect('/login');
  }

  // 2. Query public profile configuration and usage parameters safely from PostgreSQL database
  let dbUser = null;
  let notifications: any[] = [];
  let isDbError = false;

  try {
    dbUser = await prisma.user.findUnique({
      where: { id: user.id },
      select: {
        role: true,
        subscription: true,
        _count: {
          select: {
            appeals: true, // Counts total appeals generated by the user
          },
        },
      },
    });
  } catch (err) {
    console.error('Failed to fetch user database record in layout:', err);
    isDbError = true;
  }

  try {
    notifications = await prisma.notification.findMany({
      where: { userId: user.id },
      orderBy: { createdAt: 'desc' },
      take: 10,
    });
  } catch (err) {
    console.error('Failed to fetch notifications in layout:', err);
    isDbError = true;
  }

  const userRole = dbUser?.role || 'USER';
  const usageCount = dbUser?._count?.appeals || 0;
  
  const planId = dbUser?.subscription?.status === 'active' ? dbUser.subscription.planId : 'free';
  const plan = getPlanById(planId);
  const usageLimit = plan.limit;

  return (
    <AppShellClient
      userEmail={user.email || 'user@example.com'}
      userRole={userRole}
      usageCount={usageCount}
      usageLimit={usageLimit}
      initialNotifications={notifications}
    >
      {isDbError && (
        <div className="bg-rose-950/30 border border-rose-900/50 text-rose-400 p-3 text-xs text-center rounded-md mx-6 mt-6 mb-2 font-semibold">
          ⚠️ Database connection issue. Features may be limited.
        </div>
      )}
      {children}
    </AppShellClient>
  );
}
